version: "3.9"

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - .env

  # db:
  #   image: postgres:15
  #   restart: always
  #   environment:
  #     POSTGRES_DB : postgres
  #     POSTGRES_USER : postgres
  #     POSTGRES_PASSWORD : postgres

  #   ports:
  #     - "5432:5432"